baseURL = "https://nlwill.github.io/"
languageCode = "en-us"
disableKinds = ["taxonomy"]

[build]
    writeStats = true

[params]
    title = "Personal Portfolio"
    author = "William Naylor-Lovell"
    description = "About me"
    theme = "dark" # `dark` or `light`

    # Profile section
    [params.profile]
        name = "William Naylor-Lovell"
        photo = "images/profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "fab fa-linkedin-in"
        url = "https://www.linkedin.com/in/william-naylor-lovell"
        title = "LinkedIn"

        [[params.social.list]]
        icon = "fab fa-github"
        url = "https://github.com/NLWill"
        title = "GitHub"	

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "Doctor of Philosophy"
        college = "University of Warwick"
        dates = "2020 - 2025"
        thesis_title = "Perception-based adaptive tick rates: Efficient networks for immersive and stable collaborative virtual reality"
        thesis_link = "https://wrap.warwick.ac.uk/191491/"

        [[params.education.list]]
        degree = "BSc in Physics"
        college = "University of Warwick"
        dates = "2017 - 2020"

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Fluent"

    # Interests section
    [params.hobbies]
        title = "Interests"

        [[params.hobbies.list]]
        interest = "Mathematics"
		
		[[params.hobbies.list]]
        interest = "Video Games"

        [[params.hobbies.list]]
        interest = "Algorithm Development"

    [params.aboutme]
        description = "I am a programmer with particular interest in gameplay programming and algorithm development. I have just completed my Ph.D. in content-aware adaptive networking algorithms."

    # Experiences section
    [params.experiences]
        title = "Experiences"


        [[params.jobs.list]]
        position = "Volunteer Systems Developer"
        dates = "May 2025 - Present"
        company = "Aomame Space"
        #details = "#"

        [[params.jobs.list]]
        position = "Graduate Teaching Assistant"
        dates = "March 2023"
        company = "WMG, University of Warwick"
        #details = "#"

        [[params.jobs.list]]
        position = "Graduate Design Technologist"
        dates = "June 2020 - July 2020"
        company = "Mark Lovell Design Engineers"

        [[params.jobs.list]]
        position = "Undergraduate Research Assistant"
        dates = "July 2019 - May 2020"
        company = "WMG, University of Warwick"
        #details = "#"

    # Projects section
    [params.projects]
        title = "Projects"

        [[params.projects.list]]
        title = "Realtime Isosurface Generation"
        url = "https://github.com/NLWill/Realtime-Isosurface-Generation"
        description = "A C++ and HLSL project built in Unreal Engine 5 using the Marching Tetrahedra algorithm and GPU parallelism to generate meshes in real-time."
		
		[[params.projects.list]]
        title = "M.A.T.T Uprising"
        url = "https://github.com/TheFakeMatthew/GDG_GJ2025"
        description = "An asymmetric local multiplayer survival horror game in Unreal Engine 5, created for the GDG game jam 2025."

    # Skills section
    [params.skills]
        title = "Skills"

        [[params.skills.list]]
        skill = "C++, C#, HLSL, C, Python"
                
        [[params.skills.list]]
        skill = "Unreal Engine, Unity, Git"
		
        [[params.skills.list]]
        skill = "Network Development, Mathematical Analysis"
